language: python
python:
  - "2.7"
  - "3.4"
  
install: 
    - "pip install coverage"
    - "pip install coveralls"
    
script: 
    - "coverage run --source=fuckit setup.py test"
    
    
after_success:
    coveralls
    
notifications:
   email: false
